project:
  output-dir: _output
# bibliography: msens.bib
date: now
date-format: iso
format:
  html:
    toc: true              # md to exclude: {.unnumbered .unlisted}
    toc-depth: 4
    toc-expand: 1
    # toc-location: left
    number-sections: true  # md to exclude: {.unnumbered}
    code-fold: true
    code-tools: true
    embed-resources: false
execute:
  echo: true
  warning: false
  message: true
editor:
  mode: source
  markdown:
    wrap: 72
  canonical: true
editor_options:
  chunk_output_type: console
search: false
